import { ir, ref } from '../ir/builder.js';
export const FB_ALARMS_NAME = 'FB_Alarms';
/**
 * FB_Alarms MVP — latch/ack semantics for the DB_Alarms v2 contract.
 *
 *   Pass 1 (set → active)
 *     IF DB_Alarms.set_<id> THEN
 *         DB_Alarms.active_<id> := TRUE;
 *     END_IF;
 *
 *   Pass 2 (ack_all clears active when set has released)
 *     IF DB_Alarms.ack_all AND NOT DB_Alarms.set_<id> THEN
 *         DB_Alarms.active_<id> := FALSE;
 *     END_IF;
 *
 * Vendor-neutral: every reference goes through `ref.dbField('DB_Alarms', f)`
 * — backends map the namespace at render time (`"DB_Alarms".f` for Siemens,
 * `GVL_Alarms.f` for Codesys, `Alarms.f` for Rockwell).
 *
 * The Siemens-flavoured `attributes` list lives here for backward
 * compatibility — the Codesys / Rockwell renderers ignore it.
 */
export function buildFbAlarmsIR(project) {
    const machine = project.machines[0];
    if (machine.alarms.length === 0)
        return null;
    const sorted = machine.alarms
        .slice()
        .sort((a, b) => a.id.localeCompare(b.id));
    const body = [];
    body.push(ir.comment('--- Latch pass: set → active ---'));
    for (const al of sorted) {
        body.push(ir.if_(ir.refExpr(ref.dbField('DB_Alarms', `set_${al.id}`)), [
            ir.assign(ref.dbField('DB_Alarms', `active_${al.id}`), ir.boolLit(true)),
        ]));
    }
    body.push(ir.blankLine());
    body.push(ir.comment('--- Ack pass: ack_all clears active when set has released ---'));
    for (const al of sorted) {
        body.push(ir.if_(ir.bin('AND', ir.refExpr(ref.dbField('DB_Alarms', 'ack_all')), ir.not(ir.refExpr(ref.dbField('DB_Alarms', `set_${al.id}`)))), [
            ir.assign(ref.dbField('DB_Alarms', `active_${al.id}`), ir.boolLit(false)),
        ]));
    }
    body.push(ir.blankLine());
    return {
        name: FB_ALARMS_NAME,
        headerComments: [
            `==================================================================`,
            `Alarm manager (set / active / ack_all semantics)`,
            `Generated by @plccopilot/codegen-core v0.1.0`,
            `==================================================================`,
        ],
        // Backend-specific attributes are injected at render time by each backend.
        attributes: [],
        version: '0.1',
        varSections: [],
        body,
    };
}
