import {
  dbNamespaceFor,
  type DataBlockArtifactIR,
  type DataFieldIR,
  type GeneratedArtifact,
} from '@plccopilot/codegen-core';
import { ROCKWELL_DIR, ROCKWELL_NAMESPACES } from '../naming.js';

export { ROCKWELL_DIR };

/**
 * Rockwell tag-declaration POC. The Logix tag database is normally edited
 * inside Studio 5000 (or L5X-imported); these `.st`-suffixed files are a
 * textual stand-in so the IR contract is observable end-to-end.
 *
 *   DB_Global_Params → rockwell/TAG_Parameters.st  (bare `<id> : TYPE := init;`)
 *   DB_Recipes       → rockwell/TAG_Recipes.st     (bare `<id> : TYPE := init;`)
 *   DB_Alarms        → rockwell/TAG_Alarms.st      (`Alarms.<bit> : BOOL;`)
 *
 * The alarm namespace prefix is sourced from `ROCKWELL_NAMESPACES` in this
 * package — core does not know it.
 */

const PIR_TO_LOGIX: Record<string, string> = {
  Bool: 'BOOL',
  Int: 'INT',
  DInt: 'DINT',
  Real: 'REAL',
};

function logixType(t: string): string {
  return PIR_TO_LOGIX[t] ?? t.toUpperCase();
}

const TAG_FILE_BY_DB: Record<string, string> = {
  DB_Global_Params: 'TAG_Parameters.st',
  DB_Recipes: 'TAG_Recipes.st',
  DB_Alarms: 'TAG_Alarms.st',
};

function tagPathFor(db: DataBlockArtifactIR): string | null {
  const name = TAG_FILE_BY_DB[db.name];
  return name ? `${ROCKWELL_DIR}/${name}` : null;
}

function renderField(f: DataFieldIR, prefix: string): string {
  const init = f.initialValue !== undefined ? ` := ${f.initialValue}` : '';
  const c = f.comment ? `  // ${f.comment}` : '';
  return `${prefix}${f.name} : ${logixType(f.dataType)}${init};${c}`;
}

export function renderRockwellTagFile(
  db: DataBlockArtifactIR,
): GeneratedArtifact | null {
  const path = tagPathFor(db);
  if (!path) return null;

  const alias = dbNamespaceFor(db.name, ROCKWELL_NAMESPACES);
  const ns = db.dbKind === 'alarms' ? `${alias}.` : '';

  const lines: string[] = [];
  lines.push(
    `(* Rockwell tag declarations POC — ${db.name} (${db.dbKind}) *)`,
  );
  lines.push(
    `(* Generated by @plccopilot/codegen-rockwell (EXPERIMENTAL) *)`,
  );
  if (db.dbKind === 'alarms') {
    lines.push(`(* Namespace: ${alias}.<bit> *)`);
  }
  lines.push('');
  let firstFieldEmitted = false;
  for (const f of db.fields) {
    if (f.preComment) {
      if (firstFieldEmitted) lines.push('');
      lines.push(`// ${f.preComment}`);
    }
    lines.push(renderField(f, ns));
    firstFieldEmitted = true;
  }
  lines.push('');

  return {
    path,
    kind: 'st',
    content: lines.join('\n'),
  };
}

export function generateRockwellTagFiles(
  dataBlocks: readonly DataBlockArtifactIR[],
): GeneratedArtifact[] {
  const out: GeneratedArtifact[] = [];
  for (const db of dataBlocks) {
    const tag = renderRockwellTagFile(db);
    if (tag) out.push(tag);
  }
  return out;
}
