import type {
  DataBlockArtifactIR,
  DataFieldIR,
} from '@plccopilot/codegen-core';
import { CODESYS_DIR, CODESYS_NAMESPACES } from '../naming.js';

const PAD = '    ';

const PIR_TO_IEC: Record<string, string> = {
  Bool: 'BOOL',
  Int: 'INT',
  DInt: 'DINT',
  Real: 'REAL',
};

function iecType(canonicalType: string): string {
  return PIR_TO_IEC[canonicalType] ?? canonicalType.toUpperCase();
}

function gvlNameFor(db: DataBlockArtifactIR): string {
  return CODESYS_NAMESPACES[db.name] ?? db.name;
}

function codesysFieldLine(f: DataFieldIR): string {
  const init = f.initialValue !== undefined ? ` := ${f.initialValue}` : '';
  const c = f.comment ? ` (* ${f.comment} *)` : '';
  return `${PAD}${f.name} : ${iecType(f.dataType)}${init};${c}`;
}

export function renderDataBlockCodesys(db: DataBlockArtifactIR): {
  path: string;
  content: string;
} {
  const gvlName = gvlNameFor(db);
  const lines: string[] = [];
  lines.push(
    `(* ${gvlName} - generated by @plccopilot/codegen-codesys (experimental) *)`,
  );
  lines.push('');
  lines.push(`{attribute 'qualified_only'}`);
  lines.push('VAR_GLOBAL');
  let firstFieldEmitted = false;
  for (const f of db.fields) {
    if (f.preComment) {
      if (firstFieldEmitted) lines.push('');
      lines.push(`${PAD}(* ${f.preComment} *)`);
    }
    lines.push(codesysFieldLine(f));
    firstFieldEmitted = true;
  }
  lines.push('END_VAR');
  lines.push('');

  return {
    path: `${CODESYS_DIR}/${gvlName}.st`,
    content: lines.join('\n'),
  };
}
