import { CODESYS_DIR, CODESYS_NAMESPACES } from '../naming.js';
const PAD = '    ';
const PIR_TO_IEC = {
    Bool: 'BOOL',
    Int: 'INT',
    DInt: 'DINT',
    Real: 'REAL',
};
function iecType(canonicalType) {
    return PIR_TO_IEC[canonicalType] ?? canonicalType.toUpperCase();
}
function gvlNameFor(db) {
    return CODESYS_NAMESPACES[db.name] ?? db.name;
}
function codesysFieldLine(f) {
    const init = f.initialValue !== undefined ? ` := ${f.initialValue}` : '';
    const c = f.comment ? ` (* ${f.comment} *)` : '';
    return `${PAD}${f.name} : ${iecType(f.dataType)}${init};${c}`;
}
export function renderDataBlockCodesys(db) {
    const gvlName = gvlNameFor(db);
    const lines = [];
    lines.push(`(* ${gvlName} - generated by @plccopilot/codegen-codesys (experimental) *)`);
    lines.push('');
    lines.push(`{attribute 'qualified_only'}`);
    lines.push('VAR_GLOBAL');
    let firstFieldEmitted = false;
    for (const f of db.fields) {
        if (f.preComment) {
            if (firstFieldEmitted)
                lines.push('');
            lines.push(`${PAD}(* ${f.preComment} *)`);
        }
        lines.push(codesysFieldLine(f));
        firstFieldEmitted = true;
    }
    lines.push('END_VAR');
    lines.push('');
    return {
        path: `${CODESYS_DIR}/${gvlName}.st`,
        content: lines.join('\n'),
    };
}
